version: '3'
services:
  visites:
    image: edtasixm11/visites:visites
    deploy:
      replicas: 3            
    ports:
            - "80:80"
    networks:
      - mynet            
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - mynet
  redis:
    image: redis
    ports:
      - "6379:6379"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - mynet
networks:
  mynet: 
